spring:
  boot:
    admin:
      client:
        username: admin
        password: 123
        url: http://localhost:8088
        instance:
          name: client


management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "http://localhost:8088"